services:
  accounts-db:
    image: postgres
    restart: always
    ports:
      - ${ACCOUNTS_DATABASE_PORT}:5432
    environment:
      POSTGRES_USER: ${ACCOUNTS_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${ACCOUNTS_DATABASE_PASSWORD}
      POSTGRES_DB: accounts
    volumes:
      - accounts-db:/var/lib/postgresql/data

  crm-db:
    image: postgres
    restart: always
    ports:
      - ${CRM_DATABASE_PORT}:5432
    environment:
      POSTGRES_USER: ${CRM_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${CRM_DATABASE_PASSWORD}
      POSTGRES_DB: crm
    volumes:
      - crm-db:/var/lib/postgresql/data

  crm-rabbitmq:
    image: rabbitmq
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - crm-rabbitmq:/var/lib/rabbitmq

  crm-cache:
    image: redis
    environment:
      REDIS_PASSWORD: ${CRM_CACHE_PASSWORD}
      REDIS_USER: ${CRM_CACHE_USER}
      REDIS_USER_PASSWORD: ${CRM_CACHE_USER}
    ports:
      - ${CRM_CACHE_PORT}:6379
    volumes:
      - crm-cache:/data

volumes:
  accounts-db:
  crm-db:
  crm-rabbitmq:
  crm-cache:
