services:
  accounts-db:
    image: postgres
    restart: always
    ports:
      - ${ACCOUNTS_DATABASE_PORT}:5432
    environment:
      POSTGRES_USER: ${ACCOUNTS_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${ACCOUNTS_DATABASE_PASSWORD}
      POSTGRES_DB: accounts
    volumes:
      - accounts-db:/var/lib/postgresql/data

  crm-db:
    image: postgres
    restart: always
    ports:
      - ${CRM_DATABASE_PORT}:5432
    environment:
      POSTGRES_USER: ${CRM_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${CRM_DATABASE_PASSWORD}
      POSTGRES_DB: crm
    volumes:
      - crm-db:/var/lib/postgresql/data

volumes:
  accounts-db:
  crm-db:
